# This file was generated by GoReleaser. DO NOT EDIT.
cask "knowledge-tools" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "c793049ab3a83d3ceb95b3174dbfa5ec62459f9201807f66f48482da7b7c6cab"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2df55e937322161c95743bd821d2b1f2d55bdcf06024d61425f53fc886e4188"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d0dc49622f0e0821988a978014e3fa9926db5fc6ffdbae15fd64cb545a3d9905"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ae81734d4e4c95492efb61b5f788b16d571b6ac9fc2d535057fef87c666fddf"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_linux_arm64.tar.gz"
    end
  end

  name "knowledge-tools"
  desc "Host-side CLI for the personal LLM-wiki vault (compile/synthesize/resolve + daemon)"
  homepage "https://github.com/josephschmitt/knowledge-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knowledge-tools"

  postflight do
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/knowledge-tools", "#{HOMEBREW_PREFIX}/bin/kt"]
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knowledge-tools"]
  end

  # No zap stanza required

end
