# This file was generated by GoReleaser. DO NOT EDIT.
cask "knowledge-tools" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "ead9a691e494139f739d4284457153dc1d603298ec77497bcfab77c922356a4d"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "afe445d2e48360554844e7b1b127ae3cc3cc1a2570723c0647511cd383084f1f"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d4b32babfef63b54bfe0a2c43e13f31334608928840a2e47a0150356fb26b7e3"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "044de4280d0a954ce13c9753853e13bcc4e427bd947c5729b4085ae06851c8f0"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_linux_arm64.tar.gz"
    end
  end

  name "knowledge-tools"
  desc "Host-side CLI for the personal LLM-wiki vault (compile/synthesize/resolve + daemon)"
  homepage "https://github.com/josephschmitt/knowledge-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knowledge-tools"

  postflight do
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/knowledge-tools", "#{HOMEBREW_PREFIX}/bin/kt"]
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knowledge-tools"]
  end

  # No zap stanza required

end
