# This file was generated by GoReleaser. DO NOT EDIT.
cask "knowledge-tools" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "287b12bca97bc170c753593723d2091ba53273e6f02c1764005ac6dd2175cd8c"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5207d76ba4884db6538a80f998f05b6fbd2765f7d810a377f670f9fe0064121b"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0fbbc32bca19116aad6ecd7f377f51761436c53f1bfbcacf209c086c324729d6"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc244378dc90c06abf2b8fea7ab0dedcca8356353ef2a93a97d4594c991c6375"
      url "https://github.com/josephschmitt/knowledge-tools/releases/download/cli/v#{version}/knowledge-tools_#{version}_linux_arm64.tar.gz"
    end
  end

  name "knowledge-tools"
  desc "Host-side CLI for the personal LLM-wiki vault (compile/synthesize/resolve + daemon)"
  homepage "https://github.com/josephschmitt/knowledge-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knowledge-tools"

  postflight do
    system_command "/bin/ln", args: ["-sf", "#{staged_path}/knowledge-tools", "#{HOMEBREW_PREFIX}/bin/kt"]
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knowledge-tools"]
  end

  # No zap stanza required

end
