# This file was generated by GoReleaser. DO NOT EDIT.
cask "monocle" do
  version "0.48.1"

  on_macos do
    on_intel do
      sha256 "c114ca7560e939c141097057ba6e4e2cb4cff9d3b7cf8884c31bf793115ab690"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_darwin_amd64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
    on_arm do
      sha256 "df5d7753520540d7e604c22fc34674978fc6ee27bf7666ee73a9696600ae459c"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_darwin_arm64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2e318f6921837043edaf90716ad5b5ab492d363694623bafbcf7154f27449052"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_linux_amd64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
    on_arm do
      sha256 "2d5449895c8c724980575369dc295bc4c764a3565b285cb9caff4aadecc4d61c"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_linux_arm64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
  end

  name "monocle"
  desc "Terminal-based code review companion for AI coding agents"
  homepage "https://github.com/josephschmitt/monocle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monocle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monocle"]
    end
  end

  # No zap stanza required

end
