# This file was generated by GoReleaser. DO NOT EDIT.
cask "monocle" do
  version "0.47.0"

  on_macos do
    on_intel do
      sha256 "43fe15687989b5391b12f2332e95676fd0fa69918a905ef14595c188a93733f9"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_darwin_amd64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
    on_arm do
      sha256 "608ee30c74d6628d9b5f15d452b92a552961f6183e78f06dc08975b2fb9d40f1"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_darwin_arm64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1b2b5e666f7ee0e3dd9d42cbbf638a60d10fdcec4d02be1ee4c57854e6ca603"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_linux_amd64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
    on_arm do
      sha256 "a476913ca4849432f8853a35966a56597ad8c89623c52148d41b79c89f957868"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_linux_arm64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
  end

  name "monocle"
  desc "Terminal-based code review companion for AI coding agents"
  homepage "https://github.com/josephschmitt/monocle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monocle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monocle"]
    end
  end

  # No zap stanza required

end
