# This file was generated by GoReleaser. DO NOT EDIT.
cask "monocle" do
  version "0.48.0"

  on_macos do
    on_intel do
      sha256 "6f797b5e2d192f33fc77153d33d5f156dd91a1175912b813eaedc00e38301839"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_darwin_amd64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
    on_arm do
      sha256 "f0c9480249d6197ba0f8c373e020d2e74395408786f6bcc8fa30272f45dab078"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_darwin_arm64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
  end

  on_linux do
    on_intel do
      sha256 "02ae537e8f08f42456969d4a4d04a076c6fda9854332289b1652dbbb00d50eb6"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_linux_amd64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
    on_arm do
      sha256 "90e2fcdf0d0ec9e38d93a6d1cbca1b98178bba6eb239785ac4313a645960bb1f"
      url "https://github.com/josephschmitt/monocle/releases/download/v#{version}/monocle_linux_arm64.tar.gz",
        verified: "github.com/josephschmitt/monocle/"
    end
  end

  name "monocle"
  desc "Terminal-based code review companion for AI coding agents"
  homepage "https://github.com/josephschmitt/monocle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monocle"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/monocle"]
    end
  end

  # No zap stanza required

end
