# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monocle@beta < Formula
  desc "Terminal-based code review companion for AI coding agents (beta)"
  homepage "https://github.com/josephschmitt/monocle"
  version "0.43.0-beta.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.43.0-beta.3/monocle_darwin_amd64.tar.gz"
      sha256 "c138510b7053aefd517ea5828b9a7bfb709a28d7cbed71b09827e5f7cdaca07b"

      define_method(:install) do
        bin.install "monocle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.43.0-beta.3/monocle_darwin_arm64.tar.gz"
      sha256 "e3ec03c9902f87543b432c31a66700e9c7f78f27b66f077ee7b60ab43d552819"

      define_method(:install) do
        bin.install "monocle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.43.0-beta.3/monocle_linux_amd64.tar.gz"
      sha256 "151d6daddd68434469c5aefcbc998ed10b3575dba4dd16ab1b674173abe38e40"
      define_method(:install) do
        bin.install "monocle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.43.0-beta.3/monocle_linux_arm64.tar.gz"
      sha256 "eaa0c81bb37e1dab93ffbdc8c23b08aee68e506dd3952875f5d230de4a4a61b6"
      define_method(:install) do
        bin.install "monocle"
      end
    end
  end

  test do
    system "#{bin}/monocle", "--help"
  end
end
