# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monocle < Formula
  desc "Terminal-based code review companion for AI coding agents"
  homepage "https://github.com/josephschmitt/monocle"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.21.0/monocle_darwin_amd64.tar.gz"
      sha256 "2f27695cf19f91f19d4d572014a228fa76a1a25f53c9f26fae4129bf62556c79"

      define_method(:install) do
        bin.install "monocle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.21.0/monocle_darwin_arm64.tar.gz"
      sha256 "52d5472ffbea2584f282bdebed6f8fe6e83c7cf6d889bed0333d2c7e626e3d78"

      define_method(:install) do
        bin.install "monocle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.21.0/monocle_linux_amd64.tar.gz"
      sha256 "067a45c77c373a524d3393d2d4f79b0edbecf178b67575885cd3f3fe6fc26e34"
      define_method(:install) do
        bin.install "monocle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.21.0/monocle_linux_arm64.tar.gz"
      sha256 "deb5817c743afe648c77ad154cf65cb477605684ae33c978df396c9fdffb0e91"
      define_method(:install) do
        bin.install "monocle"
      end
    end
  end

  test do
    system "#{bin}/monocle", "--help"
  end
end
