# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monocle < Formula
  desc "Terminal-based code review companion for AI coding agents"
  homepage "https://github.com/josephschmitt/monocle"
  version "0.36.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.36.0/monocle_darwin_amd64.tar.gz"
      sha256 "a2f36a6e35db419a7b3bffc27d1249119045dccbd4f785718e0538c1160abe1e"

      define_method(:install) do
        bin.install "monocle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.36.0/monocle_darwin_arm64.tar.gz"
      sha256 "abe459e248a0303b9eb911d535a2e6bc24a876f9a6df7361f3dff0039ae24662"

      define_method(:install) do
        bin.install "monocle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.36.0/monocle_linux_amd64.tar.gz"
      sha256 "a3f4f2515fce28f93e811666dec4c027a4100db8321b04c1fd66137a5371aa82"
      define_method(:install) do
        bin.install "monocle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/monocle/releases/download/v0.36.0/monocle_linux_arm64.tar.gz"
      sha256 "29133eb788574a7c3b79128716ea7f89b53e2cd0b0f1e1607f0dcdb40443844c"
      define_method(:install) do
        bin.install "monocle"
      end
    end
  end

  test do
    system "#{bin}/monocle", "--help"
  end
end
