# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pj < Formula
  desc "Fast project finder CLI that searches your filesystem for git repositories and project directories"
  homepage "https://github.com/josephschmitt/pj"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/josephschmitt/pj/releases/download/v0.0.1/pj_0.0.1_darwin_amd64.tar.gz"
      sha256 "ce3085386bfe83aa9df43f9e99018508c963358edd864994ce8ff140d8dd279f"

      def install
        bin.install "pj"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/josephschmitt/pj/releases/download/v0.0.1/pj_0.0.1_darwin_arm64.tar.gz"
      sha256 "d16676252c5090f354c4d5e390ce0a06ea8593094b5b4e828337114cf06364b3"

      def install
        bin.install "pj"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/pj/releases/download/v0.0.1/pj_0.0.1_linux_amd64.tar.gz"
      sha256 "924d8e18cf60a498144f8153d615a24557e37f25d9b731c1825fdefe7999c79e"
      def install
        bin.install "pj"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/josephschmitt/pj/releases/download/v0.0.1/pj_0.0.1_linux_arm64.tar.gz"
      sha256 "c146aaf65e84da069058a3099737f7682d3473c87571cd6d27691bab1cde3e08"
      def install
        bin.install "pj"
      end
    end
  end

  test do
    system "#{bin}/pj", "--version"
  end
end
